/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotFoundRouteImport } from './routes/$notFound'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWearablesRouteImport } from './routes/_auth/wearables'
import { Route as AuthUploadsRouteImport } from './routes/_auth/uploads'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthHistoryRouteImport } from './routes/_auth/history'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthBioAgeRouteImport } from './routes/_auth/bio-age'
import { Route as AuthBiomarkersIndexRouteImport } from './routes/_auth/biomarkers.index'
import { Route as AuthActionsIndexRouteImport } from './routes/_auth/actions.index'
import { Route as AuthResultsIdRouteImport } from './routes/_auth/results.$id'
import { Route as AuthCompanionConversationIdRouteImport } from './routes/_auth/companion.$conversationId'
import { Route as AuthBiomarkersIdRouteImport } from './routes/_auth/biomarkers.$id'
import { Route as AuthActionsActionIdRouteImport } from './routes/_auth/actions.$actionId'
import { Route as AuthHealthZonesIdIndexRouteImport } from './routes/_auth/health-zones.$id.index'
import { Route as AuthActionsHealthProfileIndexRouteImport } from './routes/_auth/actions.health-profile.index'
import { Route as AuthHealthZonesIdResultIdRouteImport } from './routes/_auth/health-zones.$id.$resultId'
import { Route as AuthBiomarkersKnownCodeRouteImport } from './routes/_auth/biomarkers.known.$code'
import { Route as AuthActionsTestPackagesPackageIdRouteImport } from './routes/_auth/actions.test-packages.$packageId'
import { Route as AuthActionsHealthProfileCategoryRouteImport } from './routes/_auth/actions.health-profile.$category'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/$notFound',
  path: '/$notFound',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWearablesRoute = AuthWearablesRouteImport.update({
  id: '/_auth/wearables',
  path: '/wearables',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUploadsRoute = AuthUploadsRouteImport.update({
  id: '/_auth/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/_auth/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHistoryRoute = AuthHistoryRouteImport.update({
  id: '/_auth/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/_auth/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBioAgeRoute = AuthBioAgeRouteImport.update({
  id: '/_auth/bio-age',
  path: '/bio-age',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBiomarkersIndexRoute = AuthBiomarkersIndexRouteImport.update({
  id: '/_auth/biomarkers/',
  path: '/biomarkers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionsIndexRoute = AuthActionsIndexRouteImport.update({
  id: '/_auth/actions/',
  path: '/actions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResultsIdRoute = AuthResultsIdRouteImport.update({
  id: '/_auth/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompanionConversationIdRoute =
  AuthCompanionConversationIdRouteImport.update({
    id: '/_auth/companion/$conversationId',
    path: '/companion/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthBiomarkersIdRoute = AuthBiomarkersIdRouteImport.update({
  id: '/_auth/biomarkers/$id',
  path: '/biomarkers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionsActionIdRoute = AuthActionsActionIdRouteImport.update({
  id: '/_auth/actions/$actionId',
  path: '/actions/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHealthZonesIdIndexRoute = AuthHealthZonesIdIndexRouteImport.update({
  id: '/_auth/health-zones/$id/',
  path: '/health-zones/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionsHealthProfileIndexRoute =
  AuthActionsHealthProfileIndexRouteImport.update({
    id: '/_auth/actions/health-profile/',
    path: '/actions/health-profile/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthHealthZonesIdResultIdRoute =
  AuthHealthZonesIdResultIdRouteImport.update({
    id: '/_auth/health-zones/$id/$resultId',
    path: '/health-zones/$id/$resultId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthBiomarkersKnownCodeRoute = AuthBiomarkersKnownCodeRouteImport.update({
  id: '/_auth/biomarkers/known/$code',
  path: '/biomarkers/known/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionsTestPackagesPackageIdRoute =
  AuthActionsTestPackagesPackageIdRouteImport.update({
    id: '/_auth/actions/test-packages/$packageId',
    path: '/actions/test-packages/$packageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthActionsHealthProfileCategoryRoute =
  AuthActionsHealthProfileCategoryRouteImport.update({
    id: '/_auth/actions/health-profile/$category',
    path: '/actions/health-profile/$category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$notFound': typeof NotFoundRoute
  '/login': typeof LoginRoute
  '/bio-age': typeof AuthBioAgeRoute
  '/dashboard': typeof AuthDashboardRoute
  '/history': typeof AuthHistoryRoute
  '/profile': typeof AuthProfileRoute
  '/uploads': typeof AuthUploadsRoute
  '/wearables': typeof AuthWearablesRoute
  '/actions/$actionId': typeof AuthActionsActionIdRoute
  '/biomarkers/$id': typeof AuthBiomarkersIdRoute
  '/companion/$conversationId': typeof AuthCompanionConversationIdRoute
  '/results/$id': typeof AuthResultsIdRoute
  '/actions/': typeof AuthActionsIndexRoute
  '/biomarkers/': typeof AuthBiomarkersIndexRoute
  '/actions/health-profile/$category': typeof AuthActionsHealthProfileCategoryRoute
  '/actions/test-packages/$packageId': typeof AuthActionsTestPackagesPackageIdRoute
  '/biomarkers/known/$code': typeof AuthBiomarkersKnownCodeRoute
  '/health-zones/$id/$resultId': typeof AuthHealthZonesIdResultIdRoute
  '/actions/health-profile/': typeof AuthActionsHealthProfileIndexRoute
  '/health-zones/$id/': typeof AuthHealthZonesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$notFound': typeof NotFoundRoute
  '/login': typeof LoginRoute
  '/bio-age': typeof AuthBioAgeRoute
  '/dashboard': typeof AuthDashboardRoute
  '/history': typeof AuthHistoryRoute
  '/profile': typeof AuthProfileRoute
  '/uploads': typeof AuthUploadsRoute
  '/wearables': typeof AuthWearablesRoute
  '/actions/$actionId': typeof AuthActionsActionIdRoute
  '/biomarkers/$id': typeof AuthBiomarkersIdRoute
  '/companion/$conversationId': typeof AuthCompanionConversationIdRoute
  '/results/$id': typeof AuthResultsIdRoute
  '/actions': typeof AuthActionsIndexRoute
  '/biomarkers': typeof AuthBiomarkersIndexRoute
  '/actions/health-profile/$category': typeof AuthActionsHealthProfileCategoryRoute
  '/actions/test-packages/$packageId': typeof AuthActionsTestPackagesPackageIdRoute
  '/biomarkers/known/$code': typeof AuthBiomarkersKnownCodeRoute
  '/health-zones/$id/$resultId': typeof AuthHealthZonesIdResultIdRoute
  '/actions/health-profile': typeof AuthActionsHealthProfileIndexRoute
  '/health-zones/$id': typeof AuthHealthZonesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$notFound': typeof NotFoundRoute
  '/login': typeof LoginRoute
  '/_auth/bio-age': typeof AuthBioAgeRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/history': typeof AuthHistoryRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/uploads': typeof AuthUploadsRoute
  '/_auth/wearables': typeof AuthWearablesRoute
  '/_auth/actions/$actionId': typeof AuthActionsActionIdRoute
  '/_auth/biomarkers/$id': typeof AuthBiomarkersIdRoute
  '/_auth/companion/$conversationId': typeof AuthCompanionConversationIdRoute
  '/_auth/results/$id': typeof AuthResultsIdRoute
  '/_auth/actions/': typeof AuthActionsIndexRoute
  '/_auth/biomarkers/': typeof AuthBiomarkersIndexRoute
  '/_auth/actions/health-profile/$category': typeof AuthActionsHealthProfileCategoryRoute
  '/_auth/actions/test-packages/$packageId': typeof AuthActionsTestPackagesPackageIdRoute
  '/_auth/biomarkers/known/$code': typeof AuthBiomarkersKnownCodeRoute
  '/_auth/health-zones/$id/$resultId': typeof AuthHealthZonesIdResultIdRoute
  '/_auth/actions/health-profile/': typeof AuthActionsHealthProfileIndexRoute
  '/_auth/health-zones/$id/': typeof AuthHealthZonesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$notFound'
    | '/login'
    | '/bio-age'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/uploads'
    | '/wearables'
    | '/actions/$actionId'
    | '/biomarkers/$id'
    | '/companion/$conversationId'
    | '/results/$id'
    | '/actions/'
    | '/biomarkers/'
    | '/actions/health-profile/$category'
    | '/actions/test-packages/$packageId'
    | '/biomarkers/known/$code'
    | '/health-zones/$id/$resultId'
    | '/actions/health-profile/'
    | '/health-zones/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$notFound'
    | '/login'
    | '/bio-age'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/uploads'
    | '/wearables'
    | '/actions/$actionId'
    | '/biomarkers/$id'
    | '/companion/$conversationId'
    | '/results/$id'
    | '/actions'
    | '/biomarkers'
    | '/actions/health-profile/$category'
    | '/actions/test-packages/$packageId'
    | '/biomarkers/known/$code'
    | '/health-zones/$id/$resultId'
    | '/actions/health-profile'
    | '/health-zones/$id'
  id:
    | '__root__'
    | '/'
    | '/$notFound'
    | '/login'
    | '/_auth/bio-age'
    | '/_auth/dashboard'
    | '/_auth/history'
    | '/_auth/profile'
    | '/_auth/uploads'
    | '/_auth/wearables'
    | '/_auth/actions/$actionId'
    | '/_auth/biomarkers/$id'
    | '/_auth/companion/$conversationId'
    | '/_auth/results/$id'
    | '/_auth/actions/'
    | '/_auth/biomarkers/'
    | '/_auth/actions/health-profile/$category'
    | '/_auth/actions/test-packages/$packageId'
    | '/_auth/biomarkers/known/$code'
    | '/_auth/health-zones/$id/$resultId'
    | '/_auth/actions/health-profile/'
    | '/_auth/health-zones/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  LoginRoute: typeof LoginRoute
  AuthBioAgeRoute: typeof AuthBioAgeRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthHistoryRoute: typeof AuthHistoryRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthUploadsRoute: typeof AuthUploadsRoute
  AuthWearablesRoute: typeof AuthWearablesRoute
  AuthActionsActionIdRoute: typeof AuthActionsActionIdRoute
  AuthBiomarkersIdRoute: typeof AuthBiomarkersIdRoute
  AuthCompanionConversationIdRoute: typeof AuthCompanionConversationIdRoute
  AuthResultsIdRoute: typeof AuthResultsIdRoute
  AuthActionsIndexRoute: typeof AuthActionsIndexRoute
  AuthBiomarkersIndexRoute: typeof AuthBiomarkersIndexRoute
  AuthActionsHealthProfileCategoryRoute: typeof AuthActionsHealthProfileCategoryRoute
  AuthActionsTestPackagesPackageIdRoute: typeof AuthActionsTestPackagesPackageIdRoute
  AuthBiomarkersKnownCodeRoute: typeof AuthBiomarkersKnownCodeRoute
  AuthHealthZonesIdResultIdRoute: typeof AuthHealthZonesIdResultIdRoute
  AuthActionsHealthProfileIndexRoute: typeof AuthActionsHealthProfileIndexRoute
  AuthHealthZonesIdIndexRoute: typeof AuthHealthZonesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$notFound': {
      id: '/$notFound'
      path: '/$notFound'
      fullPath: '/$notFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/wearables': {
      id: '/_auth/wearables'
      path: '/wearables'
      fullPath: '/wearables'
      preLoaderRoute: typeof AuthWearablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/uploads': {
      id: '/_auth/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AuthUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/history': {
      id: '/_auth/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/bio-age': {
      id: '/_auth/bio-age'
      path: '/bio-age'
      fullPath: '/bio-age'
      preLoaderRoute: typeof AuthBioAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/biomarkers/': {
      id: '/_auth/biomarkers/'
      path: '/biomarkers'
      fullPath: '/biomarkers/'
      preLoaderRoute: typeof AuthBiomarkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/actions/': {
      id: '/_auth/actions/'
      path: '/actions'
      fullPath: '/actions/'
      preLoaderRoute: typeof AuthActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/results/$id': {
      id: '/_auth/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof AuthResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/companion/$conversationId': {
      id: '/_auth/companion/$conversationId'
      path: '/companion/$conversationId'
      fullPath: '/companion/$conversationId'
      preLoaderRoute: typeof AuthCompanionConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/biomarkers/$id': {
      id: '/_auth/biomarkers/$id'
      path: '/biomarkers/$id'
      fullPath: '/biomarkers/$id'
      preLoaderRoute: typeof AuthBiomarkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/actions/$actionId': {
      id: '/_auth/actions/$actionId'
      path: '/actions/$actionId'
      fullPath: '/actions/$actionId'
      preLoaderRoute: typeof AuthActionsActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/health-zones/$id/': {
      id: '/_auth/health-zones/$id/'
      path: '/health-zones/$id'
      fullPath: '/health-zones/$id/'
      preLoaderRoute: typeof AuthHealthZonesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/actions/health-profile/': {
      id: '/_auth/actions/health-profile/'
      path: '/actions/health-profile'
      fullPath: '/actions/health-profile/'
      preLoaderRoute: typeof AuthActionsHealthProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/health-zones/$id/$resultId': {
      id: '/_auth/health-zones/$id/$resultId'
      path: '/health-zones/$id/$resultId'
      fullPath: '/health-zones/$id/$resultId'
      preLoaderRoute: typeof AuthHealthZonesIdResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/biomarkers/known/$code': {
      id: '/_auth/biomarkers/known/$code'
      path: '/biomarkers/known/$code'
      fullPath: '/biomarkers/known/$code'
      preLoaderRoute: typeof AuthBiomarkersKnownCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/actions/test-packages/$packageId': {
      id: '/_auth/actions/test-packages/$packageId'
      path: '/actions/test-packages/$packageId'
      fullPath: '/actions/test-packages/$packageId'
      preLoaderRoute: typeof AuthActionsTestPackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/actions/health-profile/$category': {
      id: '/_auth/actions/health-profile/$category'
      path: '/actions/health-profile/$category'
      fullPath: '/actions/health-profile/$category'
      preLoaderRoute: typeof AuthActionsHealthProfileCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  LoginRoute: LoginRoute,
  AuthBioAgeRoute: AuthBioAgeRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthHistoryRoute: AuthHistoryRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthUploadsRoute: AuthUploadsRoute,
  AuthWearablesRoute: AuthWearablesRoute,
  AuthActionsActionIdRoute: AuthActionsActionIdRoute,
  AuthBiomarkersIdRoute: AuthBiomarkersIdRoute,
  AuthCompanionConversationIdRoute: AuthCompanionConversationIdRoute,
  AuthResultsIdRoute: AuthResultsIdRoute,
  AuthActionsIndexRoute: AuthActionsIndexRoute,
  AuthBiomarkersIndexRoute: AuthBiomarkersIndexRoute,
  AuthActionsHealthProfileCategoryRoute: AuthActionsHealthProfileCategoryRoute,
  AuthActionsTestPackagesPackageIdRoute: AuthActionsTestPackagesPackageIdRoute,
  AuthBiomarkersKnownCodeRoute: AuthBiomarkersKnownCodeRoute,
  AuthHealthZonesIdResultIdRoute: AuthHealthZonesIdResultIdRoute,
  AuthActionsHealthProfileIndexRoute: AuthActionsHealthProfileIndexRoute,
  AuthHealthZonesIdIndexRoute: AuthHealthZonesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
